/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientInfo {
  'contract' : ContractDetails,
  'contactPerson' : string,
  'email' : string,
  'company' : string,
  'address' : string,
  'phone' : string,
}
export interface ContactInfo {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContractDetails {
  'endDate' : bigint,
  'contractText' : string,
  'startDate' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Load {
  'weight' : number,
  'client' : Principal,
  'isApproved' : boolean,
  'description' : string,
  'loadingLocation' : string,
  'tracking' : [] | [TrackingUpdate],
  'assignedTransporter' : [] | [Principal],
  'confirmation' : LoadConfirmation,
  'offloadingLocation' : string,
}
export interface LoadConfirmation {
  'orderId' : string,
  'confirmationFiles' : Array<ExternalBlob>,
}
export interface TrackingUpdate {
  'status' : string,
  'timestamp' : bigint,
  'location' : string,
}
export interface TransporterDetails {
  'documents' : Array<ExternalBlob>,
  'contract' : ContractDetails,
  'contactPerson' : string,
  'email' : string,
  'company' : string,
  'address' : string,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveLoad' : ActorMethod<[string, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLoad' : ActorMethod<[string, Principal], undefined>,
  'createLoad' : ActorMethod<[Load], string>,
  'deleteLoad' : ActorMethod<[string], undefined>,
  'getAllApprovedLoads' : ActorMethod<[], Array<Load>>,
  'getAllClients' : ActorMethod<[], Array<ClientInfo>>,
  'getAllContactMessages' : ActorMethod<[], Array<[Principal, ContactInfo]>>,
  'getAllTransporters' : ActorMethod<[], Array<TransporterDetails>>,
  'getAndroidApkLink' : ActorMethod<[], [] | [string]>,
  'getCallerClientInfo' : ActorMethod<[], [] | [ClientInfo]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientInfo' : ActorMethod<[Principal], [] | [ClientInfo]>,
  'getClientLoads' : ActorMethod<[Principal], Array<Load>>,
  'getLoadTracking' : ActorMethod<[string], [] | [TrackingUpdate]>,
  'getTransporter' : ActorMethod<[Principal], [] | [TransporterDetails]>,
  'getTransporterLoads' : ActorMethod<[Principal], Array<Load>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerClientInfo' : ActorMethod<[ClientInfo], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'saveTransporterDetails' : ActorMethod<[TransporterDetails], undefined>,
  'setAndroidApkLink' : ActorMethod<[string], undefined>,
  'updateLoad' : ActorMethod<[string, Load], undefined>,
  'updateLoadTracking' : ActorMethod<[string, TrackingUpdate], undefined>,
  'uploadTransporterDoc' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];