/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LiveLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'locationName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TruckType = IDL.Variant({
  'triaxle' : IDL.Null,
  'superlinkFlatdeck' : IDL.Null,
  'sideTipper' : IDL.Null,
});
export const TrackingUpdate = IDL.Record({
  'status' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
});
export const LoadConfirmation = IDL.Record({
  'orderId' : IDL.Text,
  'confirmationFiles' : IDL.Vec(ExternalBlob),
});
export const Load = IDL.Record({
  'weight' : IDL.Float64,
  'status' : IDL.Text,
  'client' : IDL.Principal,
  'isApproved' : IDL.Bool,
  'description' : IDL.Text,
  'truckType' : TruckType,
  'loadingLocation' : IDL.Text,
  'tracking' : IDL.Opt(TrackingUpdate),
  'assignedTransporter' : IDL.Opt(IDL.Principal),
  'confirmation' : LoadConfirmation,
  'price' : IDL.Float64,
  'offloadingLocation' : IDL.Text,
});
export const Contract = IDL.Record({
  'endDate' : IDL.Int,
  'year' : IDL.Nat,
  'contractText' : IDL.Text,
  'startDate' : IDL.Int,
});
export const ClientVerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ClientInfo = IDL.Record({
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'contracts' : IDL.Vec(Contract),
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'verificationStatus' : ClientVerificationStatus,
});
export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const TransporterStatus = IDL.Record({
  'timestamp' : IDL.Int,
  'statusText' : IDL.Text,
});
export const TransporterVerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TransporterDetails = IDL.Record({
  'documents' : IDL.Vec(ExternalBlob),
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'truckType' : TruckType,
  'company' : IDL.Text,
  'contracts' : IDL.Vec(Contract),
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'verificationStatus' : TransporterVerificationStatus,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const LocationEvidence = IDL.Record({
  'transporterId' : IDL.Principal,
  'screenshot' : ExternalBlob,
  'location' : LiveLocation,
  'uploadedAt' : IDL.Int,
});
export const TruckTypeOption = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'truckType' : TruckType,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLocationEvidence' : IDL.Func([LiveLocation, ExternalBlob], [], []),
  'addYear' : IDL.Func([IDL.Nat], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'approveLoad' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLoad' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'createLoad' : IDL.Func([Load], [IDL.Text], []),
  'deleteLoad' : IDL.Func([IDL.Text], [], []),
  'deleteYear' : IDL.Func([IDL.Nat], [], []),
  'getAllApprovedLoads' : IDL.Func([], [IDL.Vec(Load)], ['query']),
  'getAllApprovedLoadsWithIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Load))],
      ['query'],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(ClientInfo)], ['query']),
  'getAllClientsWithIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ClientInfo))],
      ['query'],
    ),
  'getAllContactMessages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ContactInfo))],
      ['query'],
    ),
  'getAllPendingLoads' : IDL.Func([], [IDL.Vec(Load)], ['query']),
  'getAllPendingLoadsWithIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Load))],
      ['query'],
    ),
  'getAllTransporterStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, TransporterStatus))],
      ['query'],
    ),
  'getAllTransporters' : IDL.Func([], [IDL.Vec(TransporterDetails)], ['query']),
  'getAllTransportersWithIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, TransporterDetails))],
      ['query'],
    ),
  'getAllTransportersWithLocations' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Principal, TransporterDetails, IDL.Opt(LiveLocation))
        ),
      ],
      ['query'],
    ),
  'getAndroidApkLink' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerClientInfo' : IDL.Func([], [IDL.Opt(ClientInfo)], ['query']),
  'getCallerTransporterDetails' : IDL.Func(
      [],
      [IDL.Opt(TransporterDetails)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientContracts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Contract)],
      ['query'],
    ),
  'getClientInfo' : IDL.Func([IDL.Principal], [IDL.Opt(ClientInfo)], ['query']),
  'getClientLoads' : IDL.Func([IDL.Principal], [IDL.Vec(Load)], ['query']),
  'getContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getLoadTracking' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrackingUpdate)],
      ['query'],
    ),
  'getLocationEvidence' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LocationEvidence)],
      ['query'],
    ),
  'getTransporter' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TransporterDetails)],
      ['query'],
    ),
  'getTransporterLoadBoard' : IDL.Func([], [IDL.Vec(Load)], ['query']),
  'getTransporterLoads' : IDL.Func([IDL.Principal], [IDL.Vec(Load)], ['query']),
  'getTransporterStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TransporterStatus)],
      ['query'],
    ),
  'getTruckTypeOptions' : IDL.Func([], [IDL.Vec(TruckTypeOption)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYears' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'postContract' : IDL.Func([Contract], [], []),
  'registerClient' : IDL.Func([ClientInfo], [], []),
  'registerTransporter' : IDL.Func([TransporterDetails], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveContactInfo' : IDL.Func([ContactInfo], [], []),
  'setAndroidApkLink' : IDL.Func([IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setTransporterStatus' : IDL.Func([IDL.Text], [], []),
  'updateCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateLoad' : IDL.Func([IDL.Text, Load], [], []),
  'updateLoadTracking' : IDL.Func([IDL.Text, TrackingUpdate], [], []),
  'updateTransporterLocation' : IDL.Func([LiveLocation], [], []),
  'uploadTransporterDoc' : IDL.Func([ExternalBlob], [], []),
  'verifyClient' : IDL.Func([IDL.Principal, ClientVerificationStatus], [], []),
  'verifyTransporter' : IDL.Func(
      [IDL.Principal, TransporterVerificationStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LiveLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'locationName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TruckType = IDL.Variant({
    'triaxle' : IDL.Null,
    'superlinkFlatdeck' : IDL.Null,
    'sideTipper' : IDL.Null,
  });
  const TrackingUpdate = IDL.Record({
    'status' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
  });
  const LoadConfirmation = IDL.Record({
    'orderId' : IDL.Text,
    'confirmationFiles' : IDL.Vec(ExternalBlob),
  });
  const Load = IDL.Record({
    'weight' : IDL.Float64,
    'status' : IDL.Text,
    'client' : IDL.Principal,
    'isApproved' : IDL.Bool,
    'description' : IDL.Text,
    'truckType' : TruckType,
    'loadingLocation' : IDL.Text,
    'tracking' : IDL.Opt(TrackingUpdate),
    'assignedTransporter' : IDL.Opt(IDL.Principal),
    'confirmation' : LoadConfirmation,
    'price' : IDL.Float64,
    'offloadingLocation' : IDL.Text,
  });
  const Contract = IDL.Record({
    'endDate' : IDL.Int,
    'year' : IDL.Nat,
    'contractText' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const ClientVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ClientInfo = IDL.Record({
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'contracts' : IDL.Vec(Contract),
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'verificationStatus' : ClientVerificationStatus,
  });
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const TransporterStatus = IDL.Record({
    'timestamp' : IDL.Int,
    'statusText' : IDL.Text,
  });
  const TransporterVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TransporterDetails = IDL.Record({
    'documents' : IDL.Vec(ExternalBlob),
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'truckType' : TruckType,
    'company' : IDL.Text,
    'contracts' : IDL.Vec(Contract),
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'verificationStatus' : TransporterVerificationStatus,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const LocationEvidence = IDL.Record({
    'transporterId' : IDL.Principal,
    'screenshot' : ExternalBlob,
    'location' : LiveLocation,
    'uploadedAt' : IDL.Int,
  });
  const TruckTypeOption = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'truckType' : TruckType,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLocationEvidence' : IDL.Func([LiveLocation, ExternalBlob], [], []),
    'addYear' : IDL.Func([IDL.Nat], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'approveLoad' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLoad' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'createLoad' : IDL.Func([Load], [IDL.Text], []),
    'deleteLoad' : IDL.Func([IDL.Text], [], []),
    'deleteYear' : IDL.Func([IDL.Nat], [], []),
    'getAllApprovedLoads' : IDL.Func([], [IDL.Vec(Load)], ['query']),
    'getAllApprovedLoadsWithIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Load))],
        ['query'],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(ClientInfo)], ['query']),
    'getAllClientsWithIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ClientInfo))],
        ['query'],
      ),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ContactInfo))],
        ['query'],
      ),
    'getAllPendingLoads' : IDL.Func([], [IDL.Vec(Load)], ['query']),
    'getAllPendingLoadsWithIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Load))],
        ['query'],
      ),
    'getAllTransporterStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, TransporterStatus))],
        ['query'],
      ),
    'getAllTransporters' : IDL.Func(
        [],
        [IDL.Vec(TransporterDetails)],
        ['query'],
      ),
    'getAllTransportersWithIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, TransporterDetails))],
        ['query'],
      ),
    'getAllTransportersWithLocations' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(IDL.Principal, TransporterDetails, IDL.Opt(LiveLocation))
          ),
        ],
        ['query'],
      ),
    'getAndroidApkLink' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerClientInfo' : IDL.Func([], [IDL.Opt(ClientInfo)], ['query']),
    'getCallerTransporterDetails' : IDL.Func(
        [],
        [IDL.Opt(TransporterDetails)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientContracts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Contract)],
        ['query'],
      ),
    'getClientInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ClientInfo)],
        ['query'],
      ),
    'getClientLoads' : IDL.Func([IDL.Principal], [IDL.Vec(Load)], ['query']),
    'getContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getLoadTracking' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrackingUpdate)],
        ['query'],
      ),
    'getLocationEvidence' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LocationEvidence)],
        ['query'],
      ),
    'getTransporter' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TransporterDetails)],
        ['query'],
      ),
    'getTransporterLoadBoard' : IDL.Func([], [IDL.Vec(Load)], ['query']),
    'getTransporterLoads' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Load)],
        ['query'],
      ),
    'getTransporterStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TransporterStatus)],
        ['query'],
      ),
    'getTruckTypeOptions' : IDL.Func([], [IDL.Vec(TruckTypeOption)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYears' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'postContract' : IDL.Func([Contract], [], []),
    'registerClient' : IDL.Func([ClientInfo], [], []),
    'registerTransporter' : IDL.Func([TransporterDetails], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveContactInfo' : IDL.Func([ContactInfo], [], []),
    'setAndroidApkLink' : IDL.Func([IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setTransporterStatus' : IDL.Func([IDL.Text], [], []),
    'updateCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateLoad' : IDL.Func([IDL.Text, Load], [], []),
    'updateLoadTracking' : IDL.Func([IDL.Text, TrackingUpdate], [], []),
    'updateTransporterLocation' : IDL.Func([LiveLocation], [], []),
    'uploadTransporterDoc' : IDL.Func([ExternalBlob], [], []),
    'verifyClient' : IDL.Func(
        [IDL.Principal, ClientVerificationStatus],
        [],
        [],
      ),
    'verifyTransporter' : IDL.Func(
        [IDL.Principal, TransporterVerificationStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };