/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TrackingUpdate = IDL.Record({
  'status' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LoadConfirmation = IDL.Record({
  'orderId' : IDL.Text,
  'confirmationFiles' : IDL.Vec(ExternalBlob),
});
export const Load = IDL.Record({
  'weight' : IDL.Float64,
  'client' : IDL.Principal,
  'isApproved' : IDL.Bool,
  'description' : IDL.Text,
  'loadingLocation' : IDL.Text,
  'tracking' : IDL.Opt(TrackingUpdate),
  'assignedTransporter' : IDL.Opt(IDL.Principal),
  'confirmation' : LoadConfirmation,
  'offloadingLocation' : IDL.Text,
});
export const ContractDetails = IDL.Record({
  'endDate' : IDL.Int,
  'contractText' : IDL.Text,
  'startDate' : IDL.Int,
});
export const ClientInfo = IDL.Record({
  'contract' : ContractDetails,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const TransporterDetails = IDL.Record({
  'documents' : IDL.Vec(ExternalBlob),
  'contract' : ContractDetails,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveLoad' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLoad' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'createLoad' : IDL.Func([Load], [IDL.Text], []),
  'deleteLoad' : IDL.Func([IDL.Text], [], []),
  'getAllApprovedLoads' : IDL.Func([], [IDL.Vec(Load)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(ClientInfo)], ['query']),
  'getAllContactMessages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ContactInfo))],
      ['query'],
    ),
  'getAllTransporters' : IDL.Func([], [IDL.Vec(TransporterDetails)], ['query']),
  'getAndroidApkLink' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerClientInfo' : IDL.Func([], [IDL.Opt(ClientInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientInfo' : IDL.Func([IDL.Principal], [IDL.Opt(ClientInfo)], ['query']),
  'getClientLoads' : IDL.Func([IDL.Principal], [IDL.Vec(Load)], ['query']),
  'getLoadTracking' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TrackingUpdate)],
      ['query'],
    ),
  'getTransporter' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TransporterDetails)],
      ['query'],
    ),
  'getTransporterLoads' : IDL.Func([IDL.Principal], [IDL.Vec(Load)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerClientInfo' : IDL.Func([ClientInfo], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveContactInfo' : IDL.Func([ContactInfo], [], []),
  'saveTransporterDetails' : IDL.Func([TransporterDetails], [], []),
  'setAndroidApkLink' : IDL.Func([IDL.Text], [], []),
  'updateLoad' : IDL.Func([IDL.Text, Load], [], []),
  'updateLoadTracking' : IDL.Func([IDL.Text, TrackingUpdate], [], []),
  'uploadTransporterDoc' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TrackingUpdate = IDL.Record({
    'status' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LoadConfirmation = IDL.Record({
    'orderId' : IDL.Text,
    'confirmationFiles' : IDL.Vec(ExternalBlob),
  });
  const Load = IDL.Record({
    'weight' : IDL.Float64,
    'client' : IDL.Principal,
    'isApproved' : IDL.Bool,
    'description' : IDL.Text,
    'loadingLocation' : IDL.Text,
    'tracking' : IDL.Opt(TrackingUpdate),
    'assignedTransporter' : IDL.Opt(IDL.Principal),
    'confirmation' : LoadConfirmation,
    'offloadingLocation' : IDL.Text,
  });
  const ContractDetails = IDL.Record({
    'endDate' : IDL.Int,
    'contractText' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const ClientInfo = IDL.Record({
    'contract' : ContractDetails,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const TransporterDetails = IDL.Record({
    'documents' : IDL.Vec(ExternalBlob),
    'contract' : ContractDetails,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveLoad' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLoad' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'createLoad' : IDL.Func([Load], [IDL.Text], []),
    'deleteLoad' : IDL.Func([IDL.Text], [], []),
    'getAllApprovedLoads' : IDL.Func([], [IDL.Vec(Load)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(ClientInfo)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ContactInfo))],
        ['query'],
      ),
    'getAllTransporters' : IDL.Func(
        [],
        [IDL.Vec(TransporterDetails)],
        ['query'],
      ),
    'getAndroidApkLink' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerClientInfo' : IDL.Func([], [IDL.Opt(ClientInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ClientInfo)],
        ['query'],
      ),
    'getClientLoads' : IDL.Func([IDL.Principal], [IDL.Vec(Load)], ['query']),
    'getLoadTracking' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TrackingUpdate)],
        ['query'],
      ),
    'getTransporter' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TransporterDetails)],
        ['query'],
      ),
    'getTransporterLoads' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Load)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerClientInfo' : IDL.Func([ClientInfo], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveContactInfo' : IDL.Func([ContactInfo], [], []),
    'saveTransporterDetails' : IDL.Func([TransporterDetails], [], []),
    'setAndroidApkLink' : IDL.Func([IDL.Text], [], []),
    'updateLoad' : IDL.Func([IDL.Text, Load], [], []),
    'updateLoadTracking' : IDL.Func([IDL.Text, TrackingUpdate], [], []),
    'uploadTransporterDoc' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };