/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ClientInfo {
  'contactPerson' : string,
  'email' : string,
  'company' : string,
  'contracts' : Array<Contract>,
  'address' : string,
  'phone' : string,
  'verificationStatus' : ClientVerificationStatus,
}
export type ClientVerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface ContactInfo {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Contract {
  'endDate' : bigint,
  'contractText' : string,
  'startDate' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface LiveLocation {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'locationName' : string,
}
export interface Load {
  'weight' : number,
  'client' : Principal,
  'isApproved' : boolean,
  'description' : string,
  'truckType' : TruckType,
  'loadingLocation' : string,
  'tracking' : [] | [TrackingUpdate],
  'assignedTransporter' : [] | [Principal],
  'confirmation' : LoadConfirmation,
  'offloadingLocation' : string,
}
export interface LoadConfirmation {
  'orderId' : string,
  'confirmationFiles' : Array<ExternalBlob>,
}
export interface LocationEvidence {
  'transporterId' : Principal,
  'screenshot' : ExternalBlob,
  'location' : LiveLocation,
  'uploadedAt' : bigint,
}
export interface TrackingUpdate {
  'status' : string,
  'timestamp' : bigint,
  'location' : string,
}
export interface TransporterDetails {
  'documents' : Array<ExternalBlob>,
  'contactPerson' : string,
  'email' : string,
  'truckType' : TruckType,
  'company' : string,
  'contracts' : Array<Contract>,
  'address' : string,
  'phone' : string,
  'verificationStatus' : TransporterVerificationStatus,
}
export interface TransporterStatus {
  'timestamp' : bigint,
  'statusText' : string,
}
export type TransporterVerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export type TruckType = { 'triaxle' : null } |
  { 'superlinkFlatdeck' : null } |
  { 'sideTipper' : null };
export interface TruckTypeOption {
  'id' : bigint,
  'name' : string,
  'truckType' : TruckType,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLocationEvidence' : ActorMethod<[LiveLocation, ExternalBlob], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'approveLoad' : ActorMethod<[string, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLoad' : ActorMethod<[string, Principal], undefined>,
  'createLoad' : ActorMethod<[Load], string>,
  'deleteLoad' : ActorMethod<[string], undefined>,
  'getAllApprovedLoads' : ActorMethod<[], Array<Load>>,
  'getAllClients' : ActorMethod<[], Array<ClientInfo>>,
  'getAllClientsWithIds' : ActorMethod<[], Array<[Principal, ClientInfo]>>,
  'getAllContactMessages' : ActorMethod<[], Array<[Principal, ContactInfo]>>,
  'getAllPendingLoads' : ActorMethod<[], Array<Load>>,
  'getAllPendingLoadsWithIds' : ActorMethod<[], Array<[string, Load]>>,
  'getAllTransporterStatuses' : ActorMethod<
    [],
    Array<[Principal, TransporterStatus]>
  >,
  'getAllTransporters' : ActorMethod<[], Array<TransporterDetails>>,
  'getAllTransportersWithIds' : ActorMethod<
    [],
    Array<[Principal, TransporterDetails]>
  >,
  'getAllTransportersWithLocations' : ActorMethod<
    [],
    Array<[Principal, TransporterDetails, [] | [LiveLocation]]>
  >,
  'getAndroidApkLink' : ActorMethod<[], [] | [string]>,
  'getCallerClientInfo' : ActorMethod<[], [] | [ClientInfo]>,
  'getCallerTransporterDetails' : ActorMethod<[], [] | [TransporterDetails]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientContracts' : ActorMethod<[Principal], Array<Contract>>,
  'getClientInfo' : ActorMethod<[Principal], [] | [ClientInfo]>,
  'getClientLoads' : ActorMethod<[Principal], Array<Load>>,
  'getContracts' : ActorMethod<[], Array<Contract>>,
  'getLoadTracking' : ActorMethod<[string], [] | [TrackingUpdate]>,
  'getLocationEvidence' : ActorMethod<[Principal], Array<LocationEvidence>>,
  'getTransporter' : ActorMethod<[Principal], [] | [TransporterDetails]>,
  'getTransporterLoadBoard' : ActorMethod<[], Array<Load>>,
  'getTransporterLoads' : ActorMethod<[Principal], Array<Load>>,
  'getTransporterStatus' : ActorMethod<[Principal], [] | [TransporterStatus]>,
  'getTruckTypeOptions' : ActorMethod<[], Array<TruckTypeOption>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'postContract' : ActorMethod<[Contract], undefined>,
  'registerClient' : ActorMethod<[ClientInfo], undefined>,
  'registerTransporter' : ActorMethod<[TransporterDetails], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'setAndroidApkLink' : ActorMethod<[string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setTransporterStatus' : ActorMethod<[string], undefined>,
  'updateCredentials' : ActorMethod<[string, string], undefined>,
  'updateLoad' : ActorMethod<[string, Load], undefined>,
  'updateLoadTracking' : ActorMethod<[string, TrackingUpdate], undefined>,
  'updateTransporterLocation' : ActorMethod<[LiveLocation], undefined>,
  'uploadTransporterDoc' : ActorMethod<[ExternalBlob], undefined>,
  'verifyClient' : ActorMethod<
    [Principal, ClientVerificationStatus],
    undefined
  >,
  'verifyTransporter' : ActorMethod<
    [Principal, TransporterVerificationStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];