/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Load {
    weight: number;
    client: Principal;
    isApproved: boolean;
    description: string;
    loadingLocation: string;
    tracking?: TrackingUpdate;
    assignedTransporter?: Principal;
    confirmation: LoadConfirmation;
    offloadingLocation: string;
}
export interface TransporterDetails {
    documents: Array<ExternalBlob>;
    contract: ContractDetails;
    contactPerson: string;
    email: string;
    company: string;
    address: string;
    phone: string;
}
export interface TrackingUpdate {
    status: string;
    timestamp: bigint;
    location: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface LoadConfirmation {
    orderId: string;
    confirmationFiles: Array<ExternalBlob>;
}
export interface ContractDetails {
    endDate: bigint;
    contractText: string;
    startDate: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ClientInfo {
    contract: ContractDetails;
    contactPerson: string;
    email: string;
    company: string;
    address: string;
    phone: string;
}
export interface ContactInfo {
    name: string;
    email: string;
    message: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveLoad(loadId: string, isApproved: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignLoad(loadId: string, transporterId: Principal): Promise<void>;
    createLoad(load: Load): Promise<string>;
    deleteLoad(loadId: string): Promise<void>;
    getAllApprovedLoads(): Promise<Array<Load>>;
    getAllClients(): Promise<Array<ClientInfo>>;
    getAllContactMessages(): Promise<Array<[Principal, ContactInfo]>>;
    getAllTransporters(): Promise<Array<TransporterDetails>>;
    getAndroidApkLink(): Promise<string | null>;
    getCallerClientInfo(): Promise<ClientInfo | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientInfo(client: Principal): Promise<ClientInfo | null>;
    getClientLoads(client: Principal): Promise<Array<Load>>;
    getLoadTracking(loadId: string): Promise<TrackingUpdate | null>;
    getTransporter(transporter: Principal): Promise<TransporterDetails | null>;
    getTransporterLoads(transporter: Principal): Promise<Array<Load>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerClientInfo(clientInfo: ClientInfo): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveContactInfo(contact: ContactInfo): Promise<void>;
    saveTransporterDetails(details: TransporterDetails): Promise<void>;
    setAndroidApkLink(link: string): Promise<void>;
    updateLoad(loadId: string, load: Load): Promise<void>;
    updateLoadTracking(loadId: string, update: TrackingUpdate): Promise<void>;
    uploadTransporterDoc(blob: ExternalBlob): Promise<void>;
}
import type { ClientInfo as _ClientInfo, ContractDetails as _ContractDetails, ExternalBlob as _ExternalBlob, Load as _Load, LoadConfirmation as _LoadConfirmation, TrackingUpdate as _TrackingUpdate, TransporterDetails as _TransporterDetails, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveLoad(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLoad(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLoad(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignLoad(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLoad(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLoad(arg0, arg1);
            return result;
        }
    }
    async createLoad(arg0: Load): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoad(await to_candid_Load_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoad(await to_candid_Load_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteLoad(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLoad(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLoad(arg0);
            return result;
        }
    }
    async getAllApprovedLoads(): Promise<Array<Load>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApprovedLoads();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApprovedLoads();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(): Promise<Array<ClientInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllContactMessages(): Promise<Array<[Principal, ContactInfo]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return result;
        }
    }
    async getAllTransporters(): Promise<Array<TransporterDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransporters();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransporters();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAndroidApkLink(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAndroidApkLink();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAndroidApkLink();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerClientInfo(): Promise<ClientInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerClientInfo();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerClientInfo();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientInfo(arg0: Principal): Promise<ClientInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientInfo(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientInfo(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientLoads(arg0: Principal): Promise<Array<Load>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientLoads(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientLoads(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoadTracking(arg0: string): Promise<TrackingUpdate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoadTracking(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoadTracking(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransporter(arg0: Principal): Promise<TransporterDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransporter(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransporter(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransporterLoads(arg0: Principal): Promise<Array<Load>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransporterLoads(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransporterLoads(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerClientInfo(arg0: ClientInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerClientInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerClientInfo(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveContactInfo(arg0: ContactInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveContactInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveContactInfo(arg0);
            return result;
        }
    }
    async saveTransporterDetails(arg0: TransporterDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTransporterDetails(await to_candid_TransporterDetails_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTransporterDetails(await to_candid_TransporterDetails_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setAndroidApkLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAndroidApkLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAndroidApkLink(arg0);
            return result;
        }
    }
    async updateLoad(arg0: string, arg1: Load): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLoad(arg0, await to_candid_Load_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLoad(arg0, await to_candid_Load_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLoadTracking(arg0: string, arg1: TrackingUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLoadTracking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLoadTracking(arg0, arg1);
            return result;
        }
    }
    async uploadTransporterDoc(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadTransporterDoc(await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadTransporterDoc(await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LoadConfirmation_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoadConfirmation): Promise<LoadConfirmation> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Load_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Load): Promise<Load> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_TransporterDetails_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransporterDetails): Promise<TransporterDetails> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrackingUpdate]): TrackingUpdate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientInfo]): ClientInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransporterDetails]): Promise<TransporterDetails | null> {
    return value.length === 0 ? null : await from_candid_TransporterDetails_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    client: Principal;
    isApproved: boolean;
    description: string;
    loadingLocation: string;
    tracking: [] | [_TrackingUpdate];
    assignedTransporter: [] | [Principal];
    confirmation: _LoadConfirmation;
    offloadingLocation: string;
}): Promise<{
    weight: number;
    client: Principal;
    isApproved: boolean;
    description: string;
    loadingLocation: string;
    tracking?: TrackingUpdate;
    assignedTransporter?: Principal;
    confirmation: LoadConfirmation;
    offloadingLocation: string;
}> {
    return {
        weight: value.weight,
        client: value.client,
        isApproved: value.isApproved,
        description: value.description,
        loadingLocation: value.loadingLocation,
        tracking: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.tracking)),
        assignedTransporter: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.assignedTransporter)),
        confirmation: await from_candid_LoadConfirmation_n21(_uploadFile, _downloadFile, value.confirmation),
        offloadingLocation: value.offloadingLocation
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderId: string;
    confirmationFiles: Array<_ExternalBlob>;
}): Promise<{
    orderId: string;
    confirmationFiles: Array<ExternalBlob>;
}> {
    return {
        orderId: value.orderId,
        confirmationFiles: await from_candid_vec_n23(_uploadFile, _downloadFile, value.confirmationFiles)
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documents: Array<_ExternalBlob>;
    contract: _ContractDetails;
    contactPerson: string;
    email: string;
    company: string;
    address: string;
    phone: string;
}): Promise<{
    documents: Array<ExternalBlob>;
    contract: ContractDetails;
    contactPerson: string;
    email: string;
    company: string;
    address: string;
    phone: string;
}> {
    return {
        documents: await from_candid_vec_n23(_uploadFile, _downloadFile, value.documents),
        contract: value.contract,
        contactPerson: value.contactPerson,
        email: value.email,
        company: value.company,
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Load>): Promise<Array<Load>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Load_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransporterDetails>): Promise<Array<TransporterDetails>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TransporterDetails_n26(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_LoadConfirmation_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoadConfirmation): Promise<_LoadConfirmation> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Load_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Load): Promise<_Load> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_TransporterDetails_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransporterDetails): Promise<_TransporterDetails> {
    return await to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    client: Principal;
    isApproved: boolean;
    description: string;
    loadingLocation: string;
    tracking?: TrackingUpdate;
    assignedTransporter?: Principal;
    confirmation: LoadConfirmation;
    offloadingLocation: string;
}): Promise<{
    weight: number;
    client: Principal;
    isApproved: boolean;
    description: string;
    loadingLocation: string;
    tracking: [] | [_TrackingUpdate];
    assignedTransporter: [] | [Principal];
    confirmation: _LoadConfirmation;
    offloadingLocation: string;
}> {
    return {
        weight: value.weight,
        client: value.client,
        isApproved: value.isApproved,
        description: value.description,
        loadingLocation: value.loadingLocation,
        tracking: value.tracking ? candid_some(value.tracking) : candid_none(),
        assignedTransporter: value.assignedTransporter ? candid_some(value.assignedTransporter) : candid_none(),
        confirmation: await to_candid_LoadConfirmation_n12(_uploadFile, _downloadFile, value.confirmation),
        offloadingLocation: value.offloadingLocation
    };
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderId: string;
    confirmationFiles: Array<ExternalBlob>;
}): Promise<{
    orderId: string;
    confirmationFiles: Array<_ExternalBlob>;
}> {
    return {
        orderId: value.orderId,
        confirmationFiles: await to_candid_vec_n14(_uploadFile, _downloadFile, value.confirmationFiles)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documents: Array<ExternalBlob>;
    contract: ContractDetails;
    contactPerson: string;
    email: string;
    company: string;
    address: string;
    phone: string;
}): Promise<{
    documents: Array<_ExternalBlob>;
    contract: _ContractDetails;
    contactPerson: string;
    email: string;
    company: string;
    address: string;
    phone: string;
}> {
    return {
        documents: await to_candid_vec_n14(_uploadFile, _downloadFile, value.documents),
        contract: value.contract,
        contactPerson: value.contactPerson,
        email: value.email,
        company: value.company,
        address: value.address,
        phone: value.phone
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
